//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\any_c\source\repos\RECETA\RECETA\RECETA.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class RECETALexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, INT=11, FLOAT=12, WS=13, SEP=14, GUION=15, NEWLINE=16, TAB=17, 
		TXT=18;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "INT", "FLOAT", "WS", "SEP", "GUION", "NEWLINE", "TAB", "TXT"
	};


	public RECETALexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public RECETALexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "')'", "'RECETA'", "'PORCIONES'", "'TIEMPO PREPARACION'", "'TIEMPO COCCION'", 
		"'CALORIAS'", "'INGREDIENTES'", "'ELABORACION'", "'MIN'", "'min'", null, 
		null, "' '", "':'", "'-'", "'\n'", "'\t'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, "INT", 
		"FLOAT", "WS", "SEP", "GUION", "NEWLINE", "TAB", "TXT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "RECETA.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static RECETALexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x14', '\xB5', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\f', '\x6', '\f', '\x88', '\n', '\f', '\r', 
		'\f', '\xE', '\f', '\x89', '\x3', '\r', '\x6', '\r', '\x8D', '\n', '\r', 
		'\r', '\r', '\xE', '\r', '\x8E', '\x3', '\r', '\x3', '\r', '\x6', '\r', 
		'\x93', '\n', '\r', '\r', '\r', '\xE', '\r', '\x94', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x6', 
		'\x13', '\xA2', '\n', '\x13', '\r', '\x13', '\xE', '\x13', '\xA3', '\x3', 
		'\x13', '\a', '\x13', '\xA7', '\n', '\x13', '\f', '\x13', '\xE', '\x13', 
		'\xAA', '\v', '\x13', '\x3', '\x13', '\a', '\x13', '\xAD', '\n', '\x13', 
		'\f', '\x13', '\xE', '\x13', '\xB0', '\v', '\x13', '\x6', '\x13', '\xB2', 
		'\n', '\x13', '\r', '\x13', '\xE', '\x13', '\xB3', '\x2', '\x2', '\x14', 
		'\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', 
		'\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', 
		'\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', 
		'#', '\x13', '%', '\x14', '\x3', '\x2', '\x4', '\x3', '\x2', '\x32', ';', 
		'\x4', '\x2', '\x43', '\\', '\x63', '|', '\x2', '\xBB', '\x2', '\x3', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', 
		'\x2', '\x2', '\x3', '\'', '\x3', '\x2', '\x2', '\x2', '\x5', ')', '\x3', 
		'\x2', '\x2', '\x2', '\a', '\x30', '\x3', '\x2', '\x2', '\x2', '\t', ':', 
		'\x3', '\x2', '\x2', '\x2', '\v', 'M', '\x3', '\x2', '\x2', '\x2', '\r', 
		'\\', '\x3', '\x2', '\x2', '\x2', '\xF', '\x65', '\x3', '\x2', '\x2', 
		'\x2', '\x11', 'r', '\x3', '\x2', '\x2', '\x2', '\x13', '~', '\x3', '\x2', 
		'\x2', '\x2', '\x15', '\x82', '\x3', '\x2', '\x2', '\x2', '\x17', '\x87', 
		'\x3', '\x2', '\x2', '\x2', '\x19', '\x8C', '\x3', '\x2', '\x2', '\x2', 
		'\x1B', '\x96', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x98', '\x3', '\x2', 
		'\x2', '\x2', '\x1F', '\x9A', '\x3', '\x2', '\x2', '\x2', '!', '\x9C', 
		'\x3', '\x2', '\x2', '\x2', '#', '\x9E', '\x3', '\x2', '\x2', '\x2', '%', 
		'\xB1', '\x3', '\x2', '\x2', '\x2', '\'', '(', '\a', '+', '\x2', '\x2', 
		'(', '\x4', '\x3', '\x2', '\x2', '\x2', ')', '*', '\a', 'T', '\x2', '\x2', 
		'*', '+', '\a', 'G', '\x2', '\x2', '+', ',', '\a', '\x45', '\x2', '\x2', 
		',', '-', '\a', 'G', '\x2', '\x2', '-', '.', '\a', 'V', '\x2', '\x2', 
		'.', '/', '\a', '\x43', '\x2', '\x2', '/', '\x6', '\x3', '\x2', '\x2', 
		'\x2', '\x30', '\x31', '\a', 'R', '\x2', '\x2', '\x31', '\x32', '\a', 
		'Q', '\x2', '\x2', '\x32', '\x33', '\a', 'T', '\x2', '\x2', '\x33', '\x34', 
		'\a', '\x45', '\x2', '\x2', '\x34', '\x35', '\a', 'K', '\x2', '\x2', '\x35', 
		'\x36', '\a', 'Q', '\x2', '\x2', '\x36', '\x37', '\a', 'P', '\x2', '\x2', 
		'\x37', '\x38', '\a', 'G', '\x2', '\x2', '\x38', '\x39', '\a', 'U', '\x2', 
		'\x2', '\x39', '\b', '\x3', '\x2', '\x2', '\x2', ':', ';', '\a', 'V', 
		'\x2', '\x2', ';', '<', '\a', 'K', '\x2', '\x2', '<', '=', '\a', 'G', 
		'\x2', '\x2', '=', '>', '\a', 'O', '\x2', '\x2', '>', '?', '\a', 'R', 
		'\x2', '\x2', '?', '@', '\a', 'Q', '\x2', '\x2', '@', '\x41', '\a', '\"', 
		'\x2', '\x2', '\x41', '\x42', '\a', 'R', '\x2', '\x2', '\x42', '\x43', 
		'\a', 'T', '\x2', '\x2', '\x43', '\x44', '\a', 'G', '\x2', '\x2', '\x44', 
		'\x45', '\a', 'R', '\x2', '\x2', '\x45', '\x46', '\a', '\x43', '\x2', 
		'\x2', '\x46', 'G', '\a', 'T', '\x2', '\x2', 'G', 'H', '\a', '\x43', '\x2', 
		'\x2', 'H', 'I', '\a', '\x45', '\x2', '\x2', 'I', 'J', '\a', 'K', '\x2', 
		'\x2', 'J', 'K', '\a', 'Q', '\x2', '\x2', 'K', 'L', '\a', 'P', '\x2', 
		'\x2', 'L', '\n', '\x3', '\x2', '\x2', '\x2', 'M', 'N', '\a', 'V', '\x2', 
		'\x2', 'N', 'O', '\a', 'K', '\x2', '\x2', 'O', 'P', '\a', 'G', '\x2', 
		'\x2', 'P', 'Q', '\a', 'O', '\x2', '\x2', 'Q', 'R', '\a', 'R', '\x2', 
		'\x2', 'R', 'S', '\a', 'Q', '\x2', '\x2', 'S', 'T', '\a', '\"', '\x2', 
		'\x2', 'T', 'U', '\a', '\x45', '\x2', '\x2', 'U', 'V', '\a', 'Q', '\x2', 
		'\x2', 'V', 'W', '\a', '\x45', '\x2', '\x2', 'W', 'X', '\a', '\x45', '\x2', 
		'\x2', 'X', 'Y', '\a', 'K', '\x2', '\x2', 'Y', 'Z', '\a', 'Q', '\x2', 
		'\x2', 'Z', '[', '\a', 'P', '\x2', '\x2', '[', '\f', '\x3', '\x2', '\x2', 
		'\x2', '\\', ']', '\a', '\x45', '\x2', '\x2', ']', '^', '\a', '\x43', 
		'\x2', '\x2', '^', '_', '\a', 'N', '\x2', '\x2', '_', '`', '\a', 'Q', 
		'\x2', '\x2', '`', '\x61', '\a', 'T', '\x2', '\x2', '\x61', '\x62', '\a', 
		'K', '\x2', '\x2', '\x62', '\x63', '\a', '\x43', '\x2', '\x2', '\x63', 
		'\x64', '\a', 'U', '\x2', '\x2', '\x64', '\xE', '\x3', '\x2', '\x2', '\x2', 
		'\x65', '\x66', '\a', 'K', '\x2', '\x2', '\x66', 'g', '\a', 'P', '\x2', 
		'\x2', 'g', 'h', '\a', 'I', '\x2', '\x2', 'h', 'i', '\a', 'T', '\x2', 
		'\x2', 'i', 'j', '\a', 'G', '\x2', '\x2', 'j', 'k', '\a', '\x46', '\x2', 
		'\x2', 'k', 'l', '\a', 'K', '\x2', '\x2', 'l', 'm', '\a', 'G', '\x2', 
		'\x2', 'm', 'n', '\a', 'P', '\x2', '\x2', 'n', 'o', '\a', 'V', '\x2', 
		'\x2', 'o', 'p', '\a', 'G', '\x2', '\x2', 'p', 'q', '\a', 'U', '\x2', 
		'\x2', 'q', '\x10', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\a', 'G', '\x2', 
		'\x2', 's', 't', '\a', 'N', '\x2', '\x2', 't', 'u', '\a', '\x43', '\x2', 
		'\x2', 'u', 'v', '\a', '\x44', '\x2', '\x2', 'v', 'w', '\a', 'Q', '\x2', 
		'\x2', 'w', 'x', '\a', 'T', '\x2', '\x2', 'x', 'y', '\a', '\x43', '\x2', 
		'\x2', 'y', 'z', '\a', '\x45', '\x2', '\x2', 'z', '{', '\a', 'K', '\x2', 
		'\x2', '{', '|', '\a', 'Q', '\x2', '\x2', '|', '}', '\a', 'P', '\x2', 
		'\x2', '}', '\x12', '\x3', '\x2', '\x2', '\x2', '~', '\x7F', '\a', 'O', 
		'\x2', '\x2', '\x7F', '\x80', '\a', 'K', '\x2', '\x2', '\x80', '\x81', 
		'\a', 'P', '\x2', '\x2', '\x81', '\x14', '\x3', '\x2', '\x2', '\x2', '\x82', 
		'\x83', '\a', 'o', '\x2', '\x2', '\x83', '\x84', '\a', 'k', '\x2', '\x2', 
		'\x84', '\x85', '\a', 'p', '\x2', '\x2', '\x85', '\x16', '\x3', '\x2', 
		'\x2', '\x2', '\x86', '\x88', '\t', '\x2', '\x2', '\x2', '\x87', '\x86', 
		'\x3', '\x2', '\x2', '\x2', '\x88', '\x89', '\x3', '\x2', '\x2', '\x2', 
		'\x89', '\x87', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8A', '\x3', '\x2', 
		'\x2', '\x2', '\x8A', '\x18', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8D', 
		'\t', '\x2', '\x2', '\x2', '\x8C', '\x8B', '\x3', '\x2', '\x2', '\x2', 
		'\x8D', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8C', '\x3', '\x2', 
		'\x2', '\x2', '\x8E', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x90', 
		'\x3', '\x2', '\x2', '\x2', '\x90', '\x92', '\a', '\x30', '\x2', '\x2', 
		'\x91', '\x93', '\t', '\x2', '\x2', '\x2', '\x92', '\x91', '\x3', '\x2', 
		'\x2', '\x2', '\x93', '\x94', '\x3', '\x2', '\x2', '\x2', '\x94', '\x92', 
		'\x3', '\x2', '\x2', '\x2', '\x94', '\x95', '\x3', '\x2', '\x2', '\x2', 
		'\x95', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x96', '\x97', '\a', '\"', 
		'\x2', '\x2', '\x97', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x98', '\x99', 
		'\a', '<', '\x2', '\x2', '\x99', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x9A', 
		'\x9B', '\a', '/', '\x2', '\x2', '\x9B', ' ', '\x3', '\x2', '\x2', '\x2', 
		'\x9C', '\x9D', '\a', '\f', '\x2', '\x2', '\x9D', '\"', '\x3', '\x2', 
		'\x2', '\x2', '\x9E', '\x9F', '\a', '\v', '\x2', '\x2', '\x9F', '$', '\x3', 
		'\x2', '\x2', '\x2', '\xA0', '\xA2', '\t', '\x3', '\x2', '\x2', '\xA1', 
		'\xA0', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA3', '\x3', '\x2', '\x2', 
		'\x2', '\xA3', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA4', '\x3', 
		'\x2', '\x2', '\x2', '\xA4', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xA5', 
		'\xA7', '\a', '.', '\x2', '\x2', '\xA6', '\xA5', '\x3', '\x2', '\x2', 
		'\x2', '\xA7', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA6', '\x3', 
		'\x2', '\x2', '\x2', '\xA8', '\xA9', '\x3', '\x2', '\x2', '\x2', '\xA9', 
		'\xAE', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xA8', '\x3', '\x2', '\x2', 
		'\x2', '\xAB', '\xAD', '\x5', '\x1B', '\xE', '\x2', '\xAC', '\xAB', '\x3', 
		'\x2', '\x2', '\x2', '\xAD', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xAE', 
		'\xAC', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xAF', '\x3', '\x2', '\x2', 
		'\x2', '\xAF', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xAE', '\x3', 
		'\x2', '\x2', '\x2', '\xB1', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xB2', 
		'\xB3', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB1', '\x3', '\x2', '\x2', 
		'\x2', '\xB3', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB4', '&', '\x3', 
		'\x2', '\x2', '\x2', '\n', '\x2', '\x89', '\x8E', '\x94', '\xA3', '\xA8', 
		'\xAE', '\xB3', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
