//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\any_c\source\repos\RECETA\RECETA\RECETA.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class RECETALexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, INT=13, FLOAT=14, WS=15, SEP=16, GUION=17, 
		NEWLINE=18, TAB=19, TXT=20;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "INT", "FLOAT", "WS", "SEP", "GUION", "NEWLINE", 
		"TAB", "TXT"
	};


	public RECETALexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public RECETALexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "')'", "'RECETA'", "'PORCIONES'", "'TIEMPO PREPARACION'", "'TIEMPO COCCION'", 
		"'CALORIAS'", "'INGREDIENTES'", "'ELABORACION'", "'MIN'", "'min'", "'personas'", 
		"'kcal'", null, null, "' '", "':'", "'-'", "'\n'", "'\t'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, "INT", "FLOAT", "WS", "SEP", "GUION", "NEWLINE", "TAB", "TXT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "RECETA.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static RECETALexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x16', '\xC7', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x6', '\xE', 
		'\x9A', '\n', '\xE', '\r', '\xE', '\xE', '\xE', '\x9B', '\x3', '\xF', 
		'\x6', '\xF', '\x9F', '\n', '\xF', '\r', '\xF', '\xE', '\xF', '\xA0', 
		'\x3', '\xF', '\x3', '\xF', '\x6', '\xF', '\xA5', '\n', '\xF', '\r', '\xF', 
		'\xE', '\xF', '\xA6', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x15', '\x6', '\x15', '\xB4', '\n', '\x15', 
		'\r', '\x15', '\xE', '\x15', '\xB5', '\x3', '\x15', '\a', '\x15', '\xB9', 
		'\n', '\x15', '\f', '\x15', '\xE', '\x15', '\xBC', '\v', '\x15', '\x3', 
		'\x15', '\a', '\x15', '\xBF', '\n', '\x15', '\f', '\x15', '\xE', '\x15', 
		'\xC2', '\v', '\x15', '\x6', '\x15', '\xC4', '\n', '\x15', '\r', '\x15', 
		'\xE', '\x15', '\xC5', '\x2', '\x2', '\x16', '\x3', '\x3', '\x5', '\x4', 
		'\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', 
		'\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', 
		'\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', 
		'\x14', '\'', '\x15', ')', '\x16', '\x3', '\x2', '\x4', '\x3', '\x2', 
		'\x32', ';', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x2', '\xCD', '\x2', 
		'\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', 
		'\x3', '\x2', '\x2', '\x2', '\x3', '+', '\x3', '\x2', '\x2', '\x2', '\x5', 
		'-', '\x3', '\x2', '\x2', '\x2', '\a', '\x34', '\x3', '\x2', '\x2', '\x2', 
		'\t', '>', '\x3', '\x2', '\x2', '\x2', '\v', 'Q', '\x3', '\x2', '\x2', 
		'\x2', '\r', '`', '\x3', '\x2', '\x2', '\x2', '\xF', 'i', '\x3', '\x2', 
		'\x2', '\x2', '\x11', 'v', '\x3', '\x2', '\x2', '\x2', '\x13', '\x82', 
		'\x3', '\x2', '\x2', '\x2', '\x15', '\x86', '\x3', '\x2', '\x2', '\x2', 
		'\x17', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x19', '\x93', '\x3', '\x2', 
		'\x2', '\x2', '\x1B', '\x99', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x9E', 
		'\x3', '\x2', '\x2', '\x2', '\x1F', '\xA8', '\x3', '\x2', '\x2', '\x2', 
		'!', '\xAA', '\x3', '\x2', '\x2', '\x2', '#', '\xAC', '\x3', '\x2', '\x2', 
		'\x2', '%', '\xAE', '\x3', '\x2', '\x2', '\x2', '\'', '\xB0', '\x3', '\x2', 
		'\x2', '\x2', ')', '\xC3', '\x3', '\x2', '\x2', '\x2', '+', ',', '\a', 
		'+', '\x2', '\x2', ',', '\x4', '\x3', '\x2', '\x2', '\x2', '-', '.', '\a', 
		'T', '\x2', '\x2', '.', '/', '\a', 'G', '\x2', '\x2', '/', '\x30', '\a', 
		'\x45', '\x2', '\x2', '\x30', '\x31', '\a', 'G', '\x2', '\x2', '\x31', 
		'\x32', '\a', 'V', '\x2', '\x2', '\x32', '\x33', '\a', '\x43', '\x2', 
		'\x2', '\x33', '\x6', '\x3', '\x2', '\x2', '\x2', '\x34', '\x35', '\a', 
		'R', '\x2', '\x2', '\x35', '\x36', '\a', 'Q', '\x2', '\x2', '\x36', '\x37', 
		'\a', 'T', '\x2', '\x2', '\x37', '\x38', '\a', '\x45', '\x2', '\x2', '\x38', 
		'\x39', '\a', 'K', '\x2', '\x2', '\x39', ':', '\a', 'Q', '\x2', '\x2', 
		':', ';', '\a', 'P', '\x2', '\x2', ';', '<', '\a', 'G', '\x2', '\x2', 
		'<', '=', '\a', 'U', '\x2', '\x2', '=', '\b', '\x3', '\x2', '\x2', '\x2', 
		'>', '?', '\a', 'V', '\x2', '\x2', '?', '@', '\a', 'K', '\x2', '\x2', 
		'@', '\x41', '\a', 'G', '\x2', '\x2', '\x41', '\x42', '\a', 'O', '\x2', 
		'\x2', '\x42', '\x43', '\a', 'R', '\x2', '\x2', '\x43', '\x44', '\a', 
		'Q', '\x2', '\x2', '\x44', '\x45', '\a', '\"', '\x2', '\x2', '\x45', '\x46', 
		'\a', 'R', '\x2', '\x2', '\x46', 'G', '\a', 'T', '\x2', '\x2', 'G', 'H', 
		'\a', 'G', '\x2', '\x2', 'H', 'I', '\a', 'R', '\x2', '\x2', 'I', 'J', 
		'\a', '\x43', '\x2', '\x2', 'J', 'K', '\a', 'T', '\x2', '\x2', 'K', 'L', 
		'\a', '\x43', '\x2', '\x2', 'L', 'M', '\a', '\x45', '\x2', '\x2', 'M', 
		'N', '\a', 'K', '\x2', '\x2', 'N', 'O', '\a', 'Q', '\x2', '\x2', 'O', 
		'P', '\a', 'P', '\x2', '\x2', 'P', '\n', '\x3', '\x2', '\x2', '\x2', 'Q', 
		'R', '\a', 'V', '\x2', '\x2', 'R', 'S', '\a', 'K', '\x2', '\x2', 'S', 
		'T', '\a', 'G', '\x2', '\x2', 'T', 'U', '\a', 'O', '\x2', '\x2', 'U', 
		'V', '\a', 'R', '\x2', '\x2', 'V', 'W', '\a', 'Q', '\x2', '\x2', 'W', 
		'X', '\a', '\"', '\x2', '\x2', 'X', 'Y', '\a', '\x45', '\x2', '\x2', 'Y', 
		'Z', '\a', 'Q', '\x2', '\x2', 'Z', '[', '\a', '\x45', '\x2', '\x2', '[', 
		'\\', '\a', '\x45', '\x2', '\x2', '\\', ']', '\a', 'K', '\x2', '\x2', 
		']', '^', '\a', 'Q', '\x2', '\x2', '^', '_', '\a', 'P', '\x2', '\x2', 
		'_', '\f', '\x3', '\x2', '\x2', '\x2', '`', '\x61', '\a', '\x45', '\x2', 
		'\x2', '\x61', '\x62', '\a', '\x43', '\x2', '\x2', '\x62', '\x63', '\a', 
		'N', '\x2', '\x2', '\x63', '\x64', '\a', 'Q', '\x2', '\x2', '\x64', '\x65', 
		'\a', 'T', '\x2', '\x2', '\x65', '\x66', '\a', 'K', '\x2', '\x2', '\x66', 
		'g', '\a', '\x43', '\x2', '\x2', 'g', 'h', '\a', 'U', '\x2', '\x2', 'h', 
		'\xE', '\x3', '\x2', '\x2', '\x2', 'i', 'j', '\a', 'K', '\x2', '\x2', 
		'j', 'k', '\a', 'P', '\x2', '\x2', 'k', 'l', '\a', 'I', '\x2', '\x2', 
		'l', 'm', '\a', 'T', '\x2', '\x2', 'm', 'n', '\a', 'G', '\x2', '\x2', 
		'n', 'o', '\a', '\x46', '\x2', '\x2', 'o', 'p', '\a', 'K', '\x2', '\x2', 
		'p', 'q', '\a', 'G', '\x2', '\x2', 'q', 'r', '\a', 'P', '\x2', '\x2', 
		'r', 's', '\a', 'V', '\x2', '\x2', 's', 't', '\a', 'G', '\x2', '\x2', 
		't', 'u', '\a', 'U', '\x2', '\x2', 'u', '\x10', '\x3', '\x2', '\x2', '\x2', 
		'v', 'w', '\a', 'G', '\x2', '\x2', 'w', 'x', '\a', 'N', '\x2', '\x2', 
		'x', 'y', '\a', '\x43', '\x2', '\x2', 'y', 'z', '\a', '\x44', '\x2', '\x2', 
		'z', '{', '\a', 'Q', '\x2', '\x2', '{', '|', '\a', 'T', '\x2', '\x2', 
		'|', '}', '\a', '\x43', '\x2', '\x2', '}', '~', '\a', '\x45', '\x2', '\x2', 
		'~', '\x7F', '\a', 'K', '\x2', '\x2', '\x7F', '\x80', '\a', 'Q', '\x2', 
		'\x2', '\x80', '\x81', '\a', 'P', '\x2', '\x2', '\x81', '\x12', '\x3', 
		'\x2', '\x2', '\x2', '\x82', '\x83', '\a', 'O', '\x2', '\x2', '\x83', 
		'\x84', '\a', 'K', '\x2', '\x2', '\x84', '\x85', '\a', 'P', '\x2', '\x2', 
		'\x85', '\x14', '\x3', '\x2', '\x2', '\x2', '\x86', '\x87', '\a', 'o', 
		'\x2', '\x2', '\x87', '\x88', '\a', 'k', '\x2', '\x2', '\x88', '\x89', 
		'\a', 'p', '\x2', '\x2', '\x89', '\x16', '\x3', '\x2', '\x2', '\x2', '\x8A', 
		'\x8B', '\a', 'r', '\x2', '\x2', '\x8B', '\x8C', '\a', 'g', '\x2', '\x2', 
		'\x8C', '\x8D', '\a', 't', '\x2', '\x2', '\x8D', '\x8E', '\a', 'u', '\x2', 
		'\x2', '\x8E', '\x8F', '\a', 'q', '\x2', '\x2', '\x8F', '\x90', '\a', 
		'p', '\x2', '\x2', '\x90', '\x91', '\a', '\x63', '\x2', '\x2', '\x91', 
		'\x92', '\a', 'u', '\x2', '\x2', '\x92', '\x18', '\x3', '\x2', '\x2', 
		'\x2', '\x93', '\x94', '\a', 'm', '\x2', '\x2', '\x94', '\x95', '\a', 
		'\x65', '\x2', '\x2', '\x95', '\x96', '\a', '\x63', '\x2', '\x2', '\x96', 
		'\x97', '\a', 'n', '\x2', '\x2', '\x97', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', '\x98', '\x9A', '\t', '\x2', '\x2', '\x2', '\x99', '\x98', '\x3', 
		'\x2', '\x2', '\x2', '\x9A', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x9B', 
		'\x99', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', '\x3', '\x2', '\x2', 
		'\x2', '\x9C', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9F', '\t', 
		'\x2', '\x2', '\x2', '\x9E', '\x9D', '\x3', '\x2', '\x2', '\x2', '\x9F', 
		'\xA0', '\x3', '\x2', '\x2', '\x2', '\xA0', '\x9E', '\x3', '\x2', '\x2', 
		'\x2', '\xA0', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xA1', '\xA2', '\x3', 
		'\x2', '\x2', '\x2', '\xA2', '\xA4', '\a', '\x30', '\x2', '\x2', '\xA3', 
		'\xA5', '\t', '\x2', '\x2', '\x2', '\xA4', '\xA3', '\x3', '\x2', '\x2', 
		'\x2', '\xA5', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA4', '\x3', 
		'\x2', '\x2', '\x2', '\xA6', '\xA7', '\x3', '\x2', '\x2', '\x2', '\xA7', 
		'\x1E', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\a', '\"', '\x2', 
		'\x2', '\xA9', ' ', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xAB', '\a', 
		'<', '\x2', '\x2', '\xAB', '\"', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAD', 
		'\a', '/', '\x2', '\x2', '\xAD', '$', '\x3', '\x2', '\x2', '\x2', '\xAE', 
		'\xAF', '\a', '\f', '\x2', '\x2', '\xAF', '&', '\x3', '\x2', '\x2', '\x2', 
		'\xB0', '\xB1', '\a', '\v', '\x2', '\x2', '\xB1', '(', '\x3', '\x2', '\x2', 
		'\x2', '\xB2', '\xB4', '\t', '\x3', '\x2', '\x2', '\xB3', '\xB2', '\x3', 
		'\x2', '\x2', '\x2', '\xB4', '\xB5', '\x3', '\x2', '\x2', '\x2', '\xB5', 
		'\xB3', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB6', '\x3', '\x2', '\x2', 
		'\x2', '\xB6', '\xBA', '\x3', '\x2', '\x2', '\x2', '\xB7', '\xB9', '\a', 
		'.', '\x2', '\x2', '\xB8', '\xB7', '\x3', '\x2', '\x2', '\x2', '\xB9', 
		'\xBC', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xB8', '\x3', '\x2', '\x2', 
		'\x2', '\xBA', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xC0', '\x3', 
		'\x2', '\x2', '\x2', '\xBC', '\xBA', '\x3', '\x2', '\x2', '\x2', '\xBD', 
		'\xBF', '\x5', '\x1F', '\x10', '\x2', '\xBE', '\xBD', '\x3', '\x2', '\x2', 
		'\x2', '\xBF', '\xC2', '\x3', '\x2', '\x2', '\x2', '\xC0', '\xBE', '\x3', 
		'\x2', '\x2', '\x2', '\xC0', '\xC1', '\x3', '\x2', '\x2', '\x2', '\xC1', 
		'\xC4', '\x3', '\x2', '\x2', '\x2', '\xC2', '\xC0', '\x3', '\x2', '\x2', 
		'\x2', '\xC3', '\xB3', '\x3', '\x2', '\x2', '\x2', '\xC4', '\xC5', '\x3', 
		'\x2', '\x2', '\x2', '\xC5', '\xC3', '\x3', '\x2', '\x2', '\x2', '\xC5', 
		'\xC6', '\x3', '\x2', '\x2', '\x2', '\xC6', '*', '\x3', '\x2', '\x2', 
		'\x2', '\n', '\x2', '\x9B', '\xA0', '\xA6', '\xB5', '\xBA', '\xC0', '\xC5', 
		'\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
