//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\any_c\source\repos\RECETA\RECETA\RECETA.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="RECETAParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IRECETAVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="RECETAParser.receta"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReceta([NotNull] RECETAParser.RecetaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RECETAParser.nombre"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNombre([NotNull] RECETAParser.NombreContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RECETAParser.ingreItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIngreItem([NotNull] RECETAParser.IngreItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RECETAParser.elaItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElaItem([NotNull] RECETAParser.ElaItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RECETAParser.nom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNom([NotNull] RECETAParser.NomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RECETAParser.por"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPor([NotNull] RECETAParser.PorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RECETAParser.tp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTp([NotNull] RECETAParser.TpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RECETAParser.tc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTc([NotNull] RECETAParser.TcContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RECETAParser.clr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClr([NotNull] RECETAParser.ClrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RECETAParser.ing"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIng([NotNull] RECETAParser.IngContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RECETAParser.ela"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEla([NotNull] RECETAParser.ElaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RECETAParser.minSTR"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMinSTR([NotNull] RECETAParser.MinSTRContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RECETAParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] RECETAParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RECETAParser.min"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMin([NotNull] RECETAParser.MinContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RECETAParser.porc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPorc([NotNull] RECETAParser.PorcContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RECETAParser.calo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCalo([NotNull] RECETAParser.CaloContext context);
}
